In [61]:
import numpy as np 


In [62]:
tags = ["Noun", "Verb","Adverb"]

print(tags)

['Noun', 'Verb']


In [63]:
words = ["Dogs", "Bark","Hasheka","Eats","Breakfast","Slowly"]

word_to_index = {
    "Dogs": 0,
    "Bark": 1,
    "Hasheka": 2,
    "Eats": 3,
    "Breakfast": 4,
    "Slowly":5
}

print(word_to_index)

{'Dogs': 0, 'Bark': 1, 'Hasheka': 2, 'Eats': 3, 'Breakfast': 4}


In [64]:
init_prob = np.array([
    0.5,
    0.3,
    0.2
    
])

print(init_prob)

[0.6 0.4]


In [65]:
transition = np.array([
   [0.5, 0.4, 0.1],
    [0.3, 0.4, 0.3],
    [0.4, 0.3, 0.3]
])

print(transition)

[[0.7 0.3]
 [0.4 0.6]]


In [66]:
emission = np.array([
    [0.8, 0.2, 0.9, 0.1, 0.8, 0.1],
    [0.1, 0.9, 0.1, 0.9, 0.2, 0.1],
    [0.1, 0.1, 0.0, 0.0, 0.0, 0.8]
])

print(emission)

[[0.8 0.2 0.9 0.1 0.8]
 [0.1 0.9 0.1 0.9 0.2]]


In [67]:
log_init = np.log(init_prob + 1e-10)

log_trans = np.log(transition + 1e-10)

log_emit = np.log(emission + 1e-10)

print(log_init)

[-0.51082562 -0.91629073]


In [68]:
def viterbi(sentence):

    T = len(sentence)

    N = len(tags)

    dp = np.full((N, T), -np.inf)

    backpointer = np.zeros((N, T), dtype=int)

    dp[:, 0] = log_init + log_emit[:, sentence[0]]

    for t in range(1, T):

        for j in range(N):

            scores = (
                dp[:, t-1]
                + log_trans[:, j]
                + log_emit[j, sentence[t]]
            )

            backpointer[j, t] = np.argmax(scores)

            dp[j, t] = np.max(scores)

    best_path = [np.argmax(dp[:, -1])]

    for t in range(T-1, 0, -1):

        best_path.append(
            backpointer[best_path[-1], t]
        )

    best_path.reverse()

    return best_path

In [69]:
sentence = ["Hasheka", "Eats", "Breakfast","Slowly"]

sentence_index = [
    word_to_index[word]
    for word in sentence
]

print(sentence_index)

[2, 3, 4]


In [70]:
best_tags = viterbi(sentence_index)

print(best_tags)

[0, 1, 0]


In [71]:
print("Sentence:", sentence)

print("\nPredicted Tags:")

for word, tag in zip(sentence, best_tags):
    print(word, "->", tags[tag])

Sentence: ['Hasheka', 'Eats', 'Breakfast']

Predicted Tags:
Hasheka -> Noun
Eats -> Verb
Breakfast -> Noun
